sudo: false
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.6
      env: BUILD_DIST=true
    - python: 3.6
      env: TOXENV=coveralls
install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox-travis
script:
  - tox
deploy:
  # deploy to PyPI on tags
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    repo: typesupply/defcon
    tags: true
    all_branches: true
    condition: "$BUILD_DIST == true"
  user: anthrotype
  password:
    secure: OVsD2CqmRAeCbf0QAbfKh0Cy+7E/TW7duvr9RUopHUIhhVrPb359sIHubFiCe65VtwgMON9P2zknXHlBnwDSaoQtQ4s0kI5liEPnx5l7tUpyT06ujMK2fog58QRj/cSpJbXuJH6zInzAD06ZTIudW9LhdlndM03sYCaqNvR+QUNuRz1Kr6GZdu/U7bC7rapR7siS7LhMyzcJTeuT7+i8Tumty7akADw8qkFf3JU3PLnPbPMhp+ZGfDQcUPAl1rHkjbHuXdRuuVb/hTHRaevB2oscMLqXl6lrxSdy2LrHnNfebOA+JkWfDBmikav9EtA6NusI4+0m3tSp0XtPVhYeeQuojLOvrqvaC8cRBbJIRiXfuTTJQ9J/wN3tCsou1rV3wYPAJjO9nk4FoPjZ2i0MnXVYd+Gcix9oQxHEU7gkpwqowlb/VzVBScwJIVXfeQvKi9y2htM28J3QiQmNlxp/zi6IWdEESLW+NFtMQwuJo9ISRrnqF1S+eY13L4sHQisVmxtMhe7tg+rnG6+LsRH6sIdLulcFX71CJdu4QzyIU5K+7+MKN9v1csPCgleCW65w0UQHZXJ0WQW81E5Vsw2ksCzVZx13dVYVqGT3eTZsItcye2leUSQQJKURzZmkg+x5rUX8aWFogKnBZ8f7f06UekPo9pO16KB1wt21OZ8DwaA=
  distributions: sdist bdist_wheel
