sudo: false
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.6
      env: BUILD_DIST=true
    - python: 3.6
      env: TOXENV=coveralls
install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox-travis
script:
  - tox
deploy:
  # deploy to PyPI on tags
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    repo: typesupply/defcon
    tags: true
    all_branches: true
    condition: "$BUILD_DIST == true"
  user: anthrotype
  password:
    secure: ql58HAUjuMVmNk1hrTw126kF99dSYOpjMNLfbEOQEgRrvO6gktoCiYyLNv5IAsoXF0mi7eSpIPqDhn8ZOUwa26vc4illfC+Rg7m7RFSF2cqVD08aBtZI83uq0uapOGtvvqaWYBRE6gGLH2vrUeRR3jfbp0lITkCtG/cUcWxum5UzAfZin6vgvnetu4mxiHm6vCyoudNX9UmvUZHvn0KNn3gce3Cqvl/Sm3KyD4Rtu9+ssIOq+zx9cfwfVFWBYKqsm4RT8BSmtb1uIbKWtKzBJWo3nRkSUkk7ht+HWIXxunR2UCXC0Ug+ZZw9Lk+ClqoztN+Cso9ciy3Q/PKVL50PPPHUNHv0X+jB/8L/qeXNTMmx4f3wDMvTgllKXWMfh+OdxGaebYcYdze0Q3zObYdDOUx8hiEioOVKoMX6//MxOYYKgmKtLx/90FPQWuTbeT0gqdFt1QrGBCOMYAGhQFmC9EZv4VAIr8YjBb8fosS1jBHilTw2eiILjdc2aPcRMe/Kg998UbN+9JWPzj7bdJYC+gXCPoV3/F6nzAki8DT+Qosc+IJ1w/yqiqCegUcZh1/7JqGWDMooPTDlhgPN2BtLBUr9QqI33KuHwzqiGhAw+ziGxLBzUJLJ3AE9PEHUjM1JLavJOmNVSCzA9BDM+mVaRMejrd1Z1FNFr84piSf+EvE=
  distributions: sdist bdist_wheel
