sudo: false
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.5
      env: BUILD_DIST=true
    - python: 3.5
      env: TOXENV=coveralls
install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox-travis
script:
  - tox
deploy:
  # deploy to PyPI on tags
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    repo: typesupply/defcon
    tags: true
    all_branches: true
    condition: "$BUILD_DIST == true"
  user: anthrotype
  password:
    secure: tTYoV50bPVFHTAM9wYVwBxKGJbzh0+eHSYtXKoEv/3RO1y2DyRjutsMBDXw52EUeVgiWhJxbyIGVZb20/9IJxmQziRjyg9uRmBVCkqu6QuxcH2ffmFQZBEVan8f+e1pdt1xJXGsOLtFLQFDhhVUML747aBhHkunK9IbSq0jhJj3sHMtNFk93noPyTsHgMEyepbU8a1kMffzH5IRTlMYSXknEOfbHuF6DjFCDS3+SNZysCOIRqe6vHhILvuYTlWW/+UamFAO28quc46mKUTULCoWZpBn5Mbw+BtY0cUWVSoxWtMTXGwFhzvX4S3o/0cBhRwIoYGCcPH+tV6sm18bp/h2m2E2vwfZsT5x/wRsKv5rlfyd67rlxRco6xN0JXtFAkbcGHSaZauGuOfM6AUQnbcMNHXBU4JH/Ks1qDHljoc6CQOOGLFlxipqhvG0kdoMR4NfkrTIIZZvtZ3ad4Nc0BZ1PPAPZF76zpnrPGiZvlb+Oyo2Q39d2HnsQ1dn3VmuY0pZ3at8IWqdSgG+H+7Oz/pBuo1jxt3RtdrqjT85Bi3eqvrH61lfrFm7z3q4aXM4lLBmxkERnueAGLJuYiBJq0VYpBgsv8ERdslkUlGArAlFIWtmiSlxTaJHkZZ68n/vUNFrmEZD1ce+qqARZgEqcQU/6qZYZJP5CmRhKf4TTPJs=
  distributions: sdist bdist_wheel
